/** Shapes of the Jira Cloud REST v3 payloads this tool reads.
 *
 * Most of them are **derived**, not written: `./schema_types.ts` is generated by
 * `deno task types` from the Atlassian schemas vendored in `spec/`, and `deno task check`
 * fails if it has drifted from them.
 *
 * What remains here is what those schemas cannot express. That is not a gap in the generator —
 * it is a gap in the specification, and each case is called out below.
 */

import type { AdfNode, JiraAttachment, JiraIssueBean, JiraUser } from './schema_types.ts';

export type {
  AdfAttrs,
  AdfMark,
  AdfMarkType,
  AdfNode,
  AdfNodeType,
  AttrsOf,
  FieldMetadata,
  JiraAttachment,
  JiraComment,
  JiraCommentPage,
  JiraFieldMeta,
  JiraIssueBean,
  JiraSearchPage,
  JiraUser,
  ProjectDetails,
  StatusDetails,
} from './schema_types.ts';

/** A bare reference to another issue — a parent, or one of a parent's subtasks.
 *
 * Deliberately *not* `JiraIssueBean`: a subtask arrives with a handful of fields rather than a
 * whole issue payload, and typing it as a full issue would invite reads that are never populated.
 */
export type IssueRef = {
  id?: string;
  key: string;
  fields?: {
    summary?: string;
    status?: { name?: string } | null;
    issuetype?: { name?: string } | null;
  };
};

/**
 * The `fields` object of an issue.
 *
 * **This is the one type that cannot be derived.** The platform spec models it as
 * `{"additionalProperties": {}, "type": "object"}` — an untyped bag — so every field below would
 * come back as `any`, and the index signature that makes `customfield_NNNNN` reachable would be
 * lost. Generating it would replace real types with `any`, which is why `JiraIssueBean.fields` is
 * narrowed to this type in `JiraIssue` rather than the other way round.
 *
 * `null` is preserved rather than normalised away: an unassigned issue and an anonymous portal
 * reporter are both `null` here, and the filter engine lets a rule match that on purpose.
 */
export type JiraIssueFields = {
  summary?: string;
  description?: AdfNode | null;
  created?: string;
  updated?: string;
  reporter?: JiraUser | null;
  assignee?: JiraUser | null;
  creator?: JiraUser | null;
  issuetype?: { name?: string; subtask?: boolean } | null;
  status?: { name?: string } | null;
  priority?: { name?: string } | null;
  resolution?: { name?: string } | null;
  project?: { key?: string; name?: string } | null;
  parent?: IssueRef | null;
  subtasks?: IssueRef[];
  labels?: string[];
  components?: Array<{ name?: string }>;
  fixVersions?: Array<{ name?: string }>;
  attachment?: JiraAttachment[];
  /** Custom fields arrive as `customfield_NNNNN` alongside the named ones. */
  [key: string]: unknown;
};

/** An issue as this tool reads it: the derived envelope, with `fields` narrowed from the spec's
 * untyped bag to the shape above. */
export type JiraIssue = Omit<JiraIssueBean, 'fields'> & { fields: JiraIssueFields };

/** Attachment manifest entry: what the ADF converter needs to turn a `media` node's bare
 * attachment id into a working relative link.
 *
 * Local to this tool — it describes a file on disk, so no Atlassian schema describes it. */
export type AssetEntry = {
  id: string;
  /** The filename exactly as Jira reports it, before sanitising or collision-renaming.
   *
   * This is the only bridge between an ADF `media` node and its attachment: the node carries a
   * media-service UUID that appears nowhere in the REST payload, and its `alt` is this name. */
  sourceName: string;
  /** Sanitised, collision-free name as written inside the asset directory. */
  filename: string;
  /** Path relative to the Markdown file, e.g. `.DN-1243/screenshot.png`. */
  relativePath: string;
  contentUrl: string;
  mimeType?: string;
  size?: number;
};

export type AssetManifest = Map<string, AssetEntry>;

/**
 * Something with a name and usually an id: a component, a version, a priority, an issue type.
 *
 * Hand-written because these are the parts of a project the cache offers as menu choices, and the
 * pruned specification carries none of them — its 30-schema closure is what an *issue* payload
 * reaches, and a project's component list is not on that path. Only the two properties a menu needs
 * are declared; the responses carry more, and reading more would invite depending on it.
 */
export type NamedRef = {
  id?: string;
  name?: string;
};

/**
 * A board, from the Agile API.
 *
 * `/rest/agile/1.0/` is a different API family from the `/rest/api/3/` platform one, and it is not
 * in `spec/` at all — `deno task vendor:spec` fetches the platform document and the ADF schema, and
 * `scripts/gen_types.ts` throws on anything it does not recognise rather than weakening a type. So
 * these two are declared here, for the same reason `JiraIssueFields` is.
 */
export type AgileBoard = {
  id: number;
  name: string;
  type?: string;
};

/** A sprint. `state` is `future`, `active` or `closed`, but it is typed open: a value this tool
 * does not know is still worth offering as a filter choice. */
export type AgileSprint = {
  id: number;
  name: string;
  state?: string;
  startDate?: string;
  endDate?: string;
  originBoardId?: number;
};
