/** The config file schema — the single source of truth.
 *
 * Both the TypeScript types (via `z.infer`) and the published JSON Schema
 * (`schema/jira-fetch.schema.json`, generated by `deno task schema`) come from these
 * declarations, so an editor's autocomplete and the runtime validation can never drift apart.
 */

import { z } from 'zod';
import { ConfigError } from './errors.ts';

/** A value list entry. `null` means "absent" — an anonymous portal reporter, an unassigned
 * issue, or an unset field. It is spelled as JSON `null` rather than a magic string like
 * "anonymous" so it can never collide with a real display name. */
export const ValueMatcher = z.union([z.string(), z.null()]).describe(
  'A value to match, or null to match "absent"',
);

const valueList = (description: string) =>
  z.array(ValueMatcher).min(1, 'must list at least one value, otherwise the rule can never match')
    .describe(description);

export const TitlePredicate = z.strictObject({
  matches: z.string().min(1).describe('JavaScript regular expression tested against the summary'),
  flags: z.string().regex(/^[dgimsuvy]*$/, 'invalid regular expression flags').optional()
    .describe('Regular expression flags, e.g. "i" for case-insensitive'),
})
  .refine(
    ({ matches, flags }) => {
      try {
        new RegExp(matches, flags);
        return true;
      } catch {
        return false;
      }
    },
    { message: 'is not a valid regular expression', path: ['matches'] },
  )
  .describe('Matches the issue summary against a regular expression');

export const TicketRule = z.strictObject({
  project: z.array(z.string().min(1)).min(1).optional().describe(
    'Project prefix of the issue key, e.g. "DN". Read from the key, not from the project field, ' +
      'so this is the only predicate decidable without fetching the issue.',
  ),
  labels: valueList('Jira labels (what the UI calls "tags")').optional(),
  tags: valueList('Alias for labels').optional(),
  field: z.record(z.string().min(1), valueList('Accepted values for this field')).optional()
    .describe(
      'Field name ("Team", "Components") or raw id ("customfield_10101") mapped to accepted ' +
        'values. Names are resolved against GET /rest/api/3/field.',
    ),
  title: TitlePredicate.optional(),
  reporter: valueList('Who raised the ticket; null matches an anonymous portal submission')
    .optional(),
  assignee: valueList('Who it is assigned to; null matches an unassigned issue').optional(),
})
  .refine(
    (rule) => Object.keys(rule).length > 0,
    { message: 'needs at least one predicate; an empty rule would match every ticket' },
  )
  .describe("All predicates in a rule must match (AND). Rules within a list are OR'd.");

export const CommentRule = z.strictObject({
  author: valueList('Comment author; null matches an anonymous author'),
}).describe("Matched against a comment's author; drops the comment, never the ticket");

export const Filters = z.strictObject({
  include: z.array(TicketRule).optional().describe(
    'If non-empty, a ticket must match one of these rules to be fetched',
  ),
  exclude: z.array(TicketRule).optional().describe(
    'Matching any of these drops the ticket. Exclude beats include.',
  ),
  comments: z.strictObject({
    exclude: z.array(CommentRule).optional().describe('Comments matching these are left out'),
  }).optional().describe(
    'Exclude-only by design: an include list would mean "drop every comment not explicitly ' +
      'allowed", which is a footgun on a document meant to be an archive.',
  ),
}).describe('Which tickets are fetched, and which comments end up in the document');

export const ConfigFile = z.strictObject({
  $schema: z.string().optional().describe('Path or URL of this JSON Schema, for editor support'),
  baseUrl: z.url().optional().describe('Jira site, e.g. https://your-site.atlassian.net'),
  email: z.email().optional().describe('Atlassian account email'),
  token: z.string().min(1).optional().describe(
    'Atlassian API token. Prefer the JIRA_API_TOKEN environment variable.',
  ),
  out: z.string().min(1).optional().describe(
    'Output directory; relative paths resolve against the working directory',
  ),
  allowJql: z.boolean().optional().describe(
    'When false, the --jql flag is refused. Gates the user-facing flag only, not requests the ' +
      'tool makes on its own.',
  ),
  filters: Filters.optional(),
}).describe('Configuration for jira-fetch');

export type ValueMatcher = z.infer<typeof ValueMatcher>;
export type TitlePredicate = z.infer<typeof TitlePredicate>;
export type TicketRule = z.infer<typeof TicketRule>;
export type CommentRule = z.infer<typeof CommentRule>;
export type FiltersConfig = z.infer<typeof Filters>;
export type ConfigFile = z.infer<typeof ConfigFile>;

/** Renders Zod issues as `path: message` lines, so an error points at the offending rule. */
function formatIssues(error: z.ZodError, source: string): string {
  const lines = error.issues.map((issue) => {
    const path = issue.path.length > 0
      ? issue.path.map((p) => typeof p === 'number' ? `[${p}]` : `.${String(p)}`).join('').replace(
        /^\./,
        '',
      )
      : '(root)';
    return `  - ${path}: ${issue.message}`;
  });
  return `${source} is not a valid configuration:\n${lines.join('\n')}`;
}

/** Validates parsed JSON/YAML against the schema, raising a ConfigError that names the file. */
export function parseConfigFile(data: unknown, source: string): ConfigFile {
  const result = ConfigFile.safeParse(data);
  if (!result.success) throw new ConfigError(formatIssues(result.error, source));
  return result.data;
}

/** Validates just a filters block — used by tests and by callers holding filters on their own. */
export function parseFilters(data: unknown, source = 'filters'): FiltersConfig {
  const result = Filters.safeParse(data);
  if (!result.success) throw new ConfigError(formatIssues(result.error, source));
  return result.data;
}
