/**
 * Lays out the npm packages that carry the compiled binaries.
 *
 * Seven packages, the shape esbuild and biome use: six platform packages that each hold exactly
 * one binary and declare the `os`/`cpu` it runs on, plus the `jira-fetch` package a user actually
 * installs, which lists all six as `optionalDependencies`. npm then resolves the one that matches
 * the machine and skips the rest, so installing costs one binary rather than six.
 *
 * npm gets the **compiled** binary, which is the whole reason this is a safe channel: permissions
 * are baked in by `deno compile` at build time, so `PERMISSIONS` in build_all.ts remains the single
 * source of truth for what the MCP server may do. `deno install`/JSR would hand that decision to
 * whatever `--allow-*` flags the installing user typed.
 *
 * Everything above `stage()` is a pure function of (target, version) so it can be tested without
 * touching dist/ or the network.
 */

import { type Target, TARGETS } from './build_all.ts';

/** The npm scope the platform packages publish under. It has to be a scope its publisher owns, so
 * `assertCanPublish` in publish.ts checks `npm whoami` against this exact string. Changing the
 * account this is released from means changing it here and nowhere else. */
export const NPM_SCOPE = 'casaper';
export const MAIN_PACKAGE = 'jira-fetch';

const REPO_URL = 'https://github.com/casaper/jira-fetch';
const DESCRIPTION =
  'Fetch Jira Cloud issues into Markdown files with YAML frontmatter, attachments and all.';

const repository = { type: 'git', url: `git+${REPO_URL}.git` };

/** npm's name for a platform, e.g. `darwin-arm64` — `process.platform`-`process.arch`, which is
 * what the shim computes at runtime to find its own binary. */
export const platformSuffix = (target: Target): string => `${target.os}-${target.cpu}`;

export const platformPackage = (target: Target): string =>
  `@${NPM_SCOPE}/${MAIN_PACKAGE}-${platformSuffix(target)}`;

/** The binary's name *inside* its package — deliberately not the release asset's name. The asset
 * has to say which platform it is because six of them sit in one directory; inside a package that
 * only exists for one platform, saying it again would only give the shim more to guess. */
export const binaryName = (target: Target): string =>
  target.os === 'win32' ? 'jira-fetch.exe' : 'jira-fetch';

export type PlatformManifest = {
  name: string;
  version: string;
  description: string;
  license: string;
  homepage: string;
  repository: typeof repository;
  os: string[];
  cpu: string[];
  files: string[];
  preferUnplugged: boolean;
};

export const platformManifest = (target: Target, version: string): PlatformManifest => ({
  name: platformPackage(target),
  version,
  description: `The jira-fetch binary for ${platformSuffix(target)}.`,
  license: 'MIT',
  homepage: REPO_URL,
  repository,
  // What makes npm install one of these six and not the others.
  os: [target.os],
  cpu: [target.cpu],
  files: [binaryName(target)],
  // Yarn PnP otherwise keeps the package zipped, and you cannot exec a file inside a zip.
  preferUnplugged: true,
});

export type MainManifest = {
  name: string;
  version: string;
  description: string;
  license: string;
  homepage: string;
  repository: typeof repository;
  bugs: { url: string };
  keywords: string[];
  bin: Record<string, string>;
  files: string[];
  engines: { node: string };
  optionalDependencies: Record<string, string>;
};

export const mainManifest = (version: string): MainManifest => ({
  name: MAIN_PACKAGE,
  version,
  description: DESCRIPTION,
  license: 'MIT',
  homepage: REPO_URL,
  repository,
  bugs: { url: `${REPO_URL}/issues` },
  keywords: ['jira', 'atlassian', 'markdown', 'cli', 'mcp', 'mcp-server'],
  bin: { [MAIN_PACKAGE]: 'bin/jira-fetch.mjs' },
  files: ['bin/jira-fetch.mjs'],
  engines: { node: '>=18' },
  // Pinned exactly, not caret-ranged: the shim resolves a sibling by name and expects the binary
  // that was compiled from this very source tree.
  optionalDependencies: Object.fromEntries(
    TARGETS.map((target) => [platformPackage(target), version]),
  ),
});

/** The `bin` entry npm links onto PATH. It finds the platform package's binary and hands over.
 *
 * `String.raw` so the `\n` sequences below reach the generated file as two characters rather than
 * being collapsed into real newlines by this template literal, which would leave unterminated
 * string literals in the shipped JavaScript.
 *
 * It writes to **stderr only**. In `jira-fetch mcp` stdout is the JSON-RPC stream, and a single
 * stray line from the wrapper would corrupt the session far from its cause. */
export const SHIM = String.raw`#!/usr/bin/env node
// Generated by scripts/npm_package.ts. Do not edit.

import { spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';

const platform = process.platform + '-' + process.arch;
const pkg = '@casaper/jira-fetch-' + platform;
const file = process.platform === 'win32' ? 'jira-fetch.exe' : 'jira-fetch';

let binary;
try {
  binary = createRequire(import.meta.url).resolve(pkg + '/' + file);
} catch {
  process.stderr.write(
    'jira-fetch: no prebuilt binary for ' + platform + '.\n' +
      'One binary per platform ships as an optional dependency, so this usually means the\n' +
      'install ran with --no-optional or --omit=optional, or this platform is not built.\n' +
      'Binaries for every supported platform: https://github.com/casaper/jira-fetch/releases\n',
  );
  process.exit(1);
}

// stdio: 'inherit' gives the child the real file descriptors rather than pipes this process
// forwards. 'jira-fetch mcp' speaks JSON-RPC on stdio and stops when its stdin ends, so it has to
// see the actual stream: anything relayed here would add a place for the protocol to break.
const { status, signal, error } = spawnSync(binary, process.argv.slice(2), { stdio: 'inherit' });

if (error) {
  process.stderr.write('jira-fetch: cannot run ' + binary + ': ' + error.message + '\n');
  process.exit(1);
}
// Re-raise rather than translate to an exit code: a killed child should look killed to whoever
// ran this, not like a program that chose to fail.
if (signal) {
  process.kill(process.pid, signal);
}
// jira-fetch's exit codes are part of its contract — 2 for usage, 3 for "everything was filtered"
// — so the wrapper must pass them through untouched.
process.exit(status === null ? 1 : status);
`;

const json = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`;

export type StagedPackage = { name: string; dir: string };

/**
 * Writes the seven packages under `out`, copying each binary straight out of `dist` — the same
 * bytes the GitHub release gets, so nothing is compiled twice. `dist` is a parameter only so the
 * suite can stage from a temp directory instead of needing a real cross-compile.
 *
 * The returned order is the order they must be published in: platform packages first, then the
 * main one, so that by the time `jira-fetch` appears on the registry its `optionalDependencies`
 * already resolve.
 */
export const stage = async (
  version: string,
  out: string,
  dist = 'dist',
): Promise<StagedPackage[]> => {
  await Deno.remove(out, { recursive: true }).catch(() => {});

  const staged: StagedPackage[] = [];

  for (const target of TARGETS) {
    const dir = `${out}/${platformSuffix(target)}`;
    await Deno.mkdir(dir, { recursive: true });
    await Deno.writeTextFile(`${dir}/package.json`, json(platformManifest(target, version)));

    const binary = `${dir}/${binaryName(target)}`;
    await Deno.copyFile(`${dist}/${target.name}`, binary);
    // Deno.copyFile carries the mode over, but the executable bit is the one thing that would fail
    // on a user's machine and not here, so it is set rather than assumed.
    if (Deno.build.os !== 'windows') await Deno.chmod(binary, 0o755);

    staged.push({ name: platformPackage(target), dir });
  }

  const main = `${out}/${MAIN_PACKAGE}`;
  await Deno.mkdir(`${main}/bin`, { recursive: true });
  await Deno.writeTextFile(`${main}/package.json`, json(mainManifest(version)));
  await Deno.writeTextFile(`${main}/bin/jira-fetch.mjs`, SHIM);
  if (Deno.build.os !== 'windows') await Deno.chmod(`${main}/bin/jira-fetch.mjs`, 0o755);
  // npm publishes both regardless of `files`; they are what the registry page shows.
  await Deno.copyFile('README.md', `${main}/README.md`);
  await Deno.copyFile('LICENSE', `${main}/LICENSE`);

  staged.push({ name: MAIN_PACKAGE, dir: main });
  return staged;
};

if (import.meta.main) {
  // A convenience for looking at what would be published — `deno task npm:pack`. The release path
  // does not come through here: `publish.ts` passes the version it has already checked against
  // src/cli/args.ts, so this reading of deno.json can never be what a published package carries.
  const { version } = JSON.parse(await Deno.readTextFile('deno.json'));
  const packages = await stage(version, 'dist/npm');
  console.log(`staged ${packages.length} packages for ${version} in dist/npm:`);
  for (const pkg of packages) console.log(`  ${pkg.name}  ->  ${pkg.dir}`);
  console.log('\nInspect one with:  npm pack --dry-run ./dist/npm/jira-fetch');
}
